### ISSUE TITLE
Add tag for 0.9 release

### ISSUE THREAD

**Issue by richardfearn** [deltaray/clide#3]
I think the 0.9 release was created from commit 58add8e. It would be helpful to have a tag for that release.

**Comment by deltaray** [comment]
Sorry about the extreme delay on this.  It does seem to be close, but not quite (spec file is different). I think I must have released the tar.gz file on the site in between commits (Naughty!).  I've tagged 58add8e anyways and will try to do better in the future.

**Comment by richardfearn** [comment]
Thanks!
